name: "$(Year:yyyy).$(Month).$(BuildID)"

trigger:
  batch: true
  branches:
    include:
      - main

pr: none

resources:
  repositories:
    - repository: jdk-harness
      type: git
      name: Devdiv/jdk-harness
      #ref: refs/heads/main
      ref: refs/heads/shwethac/test-release
      # refs/heads/shwethac/test-release  point to feature in azure devops
      #project: "Devdiv"

variables:
  JTREG_VERSION: "6.1"

stages:
  - template: /.devops/jdk11u/release.yml@jdk-harness
